sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: KL2jMXefVLPeGnIwM8zR+Dk6C6KDb/qDqyZISFnUlh0ESMuUq8k31xmVlwuNZLYUreV06qc0XEB0lvVxv/xBFJewg/ocgSw74IEOCelH3QXy2Nk300GmE4nyswKAI1pA0++z2lkFnXP/fbnJhBuUuMb8QPWXBeQD3bIpwUfO97sUQU31cCGvC52tnlxlf7fRN+EP0kyrydwL2Dl6w9zg2rKSb0EVNmenMoEJBRrSbEfc1bT+A2l6n32ClTLFZdTrMfOqOpPLrrVtD0i5zBqHYLkA8NxJGbEueqofhEBIhuLCiQtlG9xTa6v2zocxi6jdJDrwERLXLfahYM14IuVFx7LfQrG2CCI3hrTMuXLEs+B3CizMd7oyw/ZY9A35s+M8SAQtynIDulY+vTqhFp34o188Z6jfgyS2ut8sGIW7Urc/33FOBJBcf4Q9SOFqodSWS50t6ILbbOZlz3uL+UX4qFhHMylLjuTJQrnv7p96eMYLOJQmagaILOCVALhVvDSs7ZndursxARMRg8sRQZUe7ajtBBUHzGX2AN863IOHM9ggfPgCKlWohCPYInDmAPeZ1gb8AyyLGOni9bsL8f3+4xJAJc8yA88Bnnchq51jfn7uT3N9ATaVrEYzvh6v06vVpuCuXw+LrPlP8bgR7kXPw82XHkTWJ+3akefjnIC5D/E=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Light-Life-and-Love-Selections-from-the-German-Mystics-of-the-Middle-Ages_4664
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy